package owr.d3.generator.pulley.export.dfx;

public class DXFFileFormatR14 implements IDXFContentCreator {

	DXFFileFormatR14() {
	}

	@Override
	public void createDXFContent(double[][] vertexes, StringBuilder sb) {

		appendBegin(sb, vertexes.length);
		appendVertexes(sb, vertexes);
		appendEnd(sb);

	}

	private void appendVertexes(StringBuilder sb, double[][] vertexes) {

		for (int i = 0; i < vertexes.length; i++) {

			sb.append(" 10\n");
			sb.append(vertexes[i][0]);
			sb.append("\n");
			sb.append(" 20\n");
			sb.append(vertexes[i][1]);
			sb.append("\n");
			sb.append(" 30\n");
			sb.append("0.0\n");
		}
	}

	private void appendEnd(StringBuilder sb) {

		sb.append("  0\n");
		sb.append("ENDSEC\n");
		sb.append("  0\n");
		sb.append("SECTION\n");
		sb.append("  2\n");
		sb.append("OBJECTS\n");
		sb.append("  0\n");
		sb.append("DICTIONARY\n");
		sb.append("  5\n");
		sb.append("C\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbDictionary\n");
		sb.append("  3\n");
		sb.append("ACAD_GROUP\n");
		sb.append("350\n");
		sb.append("D\n");
		sb.append("  3\n");
		sb.append("ACAD_MLINESTYLE\n");
		sb.append("350\n");
		sb.append("17\n");
		sb.append("  0\n");
		sb.append("DICTIONARY\n");
		sb.append("  5\n");
		sb.append("D\n");
		sb.append("330\n");
		sb.append("C\n");
		sb.append("100\n");
		sb.append("AcDbDictionary\n");
		sb.append("  0\n");
		sb.append("DICTIONARY\n");
		sb.append("  5\n");
		sb.append("1A\n");
		sb.append("330\n");
		sb.append("C\n");
		sb.append("100\n");
		sb.append("AcDbDictionary\n");
		sb.append("  0\n");
		sb.append("DICTIONARY\n");
		sb.append("  5\n");
		sb.append("17\n");
		sb.append("330\n");
		sb.append("C\n");
		sb.append("100\n");
		sb.append("AcDbDictionary\n");
		sb.append("  3\n");
		sb.append("STANDARD\n");
		sb.append("350\n");
		sb.append("18\n");
		sb.append("  0\n");
		sb.append("DICTIONARY\n");
		sb.append("  5\n");
		sb.append("19\n");
		sb.append("330\n");
		sb.append("C\n");
		sb.append("100\n");
		sb.append("AcDbDictionary\n");
		sb.append("  0\n");
		sb.append("ENDSEC\n");
		sb.append("  0\n");
		sb.append("EOF");
	}

	private void appendBegin(StringBuilder sb, int vertexesCount) {
		sb.append("  0\n");
		sb.append("SECTION\n");
		sb.append("  2\n");
		sb.append("HEADER\n");
		sb.append("  9\n");
		sb.append("$ACADVER\n");
		sb.append("  1\n");
		sb.append("AC1014\n");
		sb.append("  9\n");
		sb.append("$HANDSEED\n");
		sb.append("  5\n");
		sb.append("FFFF\n");
		sb.append("  9\n");
		sb.append("$MEASUREMENT\n");
		sb.append(" 70\n");
		sb.append("     1\n");
		sb.append("  0\n");
		sb.append("ENDSEC\n");
		sb.append("  0\n");
		sb.append("SECTION\n");
		sb.append("  2\n");
		sb.append("TABLES\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("VPORT\n");
		sb.append("  5\n");
		sb.append("8\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     4\n");
		sb.append("  0\n");
		sb.append("VPORT\n");
		sb.append("  5\n");
		sb.append("2E\n");
		sb.append("330\n");
		sb.append("8\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbViewportTableRecord\n");
		sb.append("  2\n");
		sb.append("*ACTIVE\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append(" 10\n");
		sb.append("0.0\n");
		sb.append(" 20\n");
		sb.append("0.0\n");
		sb.append(" 11\n");
		sb.append("1.0\n");
		sb.append(" 21\n");
		sb.append("1.0\n");
		sb.append(" 12\n");
		sb.append("210.0\n");
		sb.append(" 22\n");
		sb.append("148.5\n");
		sb.append(" 13\n");
		sb.append("0.0\n");
		sb.append(" 23\n");
		sb.append("0.0\n");
		sb.append(" 14\n");
		sb.append("10.0\n");
		sb.append(" 24\n");
		sb.append("10.0\n");
		sb.append(" 15\n");
		sb.append("10.0\n");
		sb.append(" 25\n");
		sb.append("10.0\n");
		sb.append(" 16\n");
		sb.append("0.0\n");
		sb.append(" 26\n");
		sb.append("0.0\n");
		sb.append(" 36\n");
		sb.append("1.0\n");
		sb.append(" 17\n");
		sb.append("0.0\n");
		sb.append(" 27\n");
		sb.append("0.0\n");
		sb.append(" 37\n");
		sb.append("0.0\n");
		sb.append(" 40\n");
		sb.append("341.0\n");
		sb.append(" 41\n");
		sb.append("1.24\n");
		sb.append(" 42\n");
		sb.append("50.0\n");
		sb.append(" 43\n");
		sb.append("0.0\n");
		sb.append(" 44\n");
		sb.append("0.0\n");
		sb.append(" 50\n");
		sb.append("0.0\n");
		sb.append(" 51\n");
		sb.append("0.0\n");
		sb.append(" 71\n");
		sb.append("     0\n");
		sb.append(" 72\n");
		sb.append("   100\n");
		sb.append(" 73\n");
		sb.append("     1\n");
		sb.append(" 74\n");
		sb.append("     3\n");
		sb.append(" 75\n");
		sb.append("     0\n");
		sb.append(" 76\n");
		sb.append("     0\n");
		sb.append(" 77\n");
		sb.append("     0\n");
		sb.append(" 78\n");
		sb.append("     0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("LTYPE\n");
		sb.append("  5\n");
		sb.append("5\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     1\n");
		sb.append("  0\n");
		sb.append("LTYPE\n");
		sb.append("  5\n");
		sb.append("14\n");
		sb.append("330\n");
		sb.append("5\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbLinetypeTableRecord\n");
		sb.append("  2\n");
		sb.append("BYBLOCK\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  3\n");
		sb.append("\n");
		sb.append(" 72\n");
		sb.append("    65\n");
		sb.append(" 73\n");
		sb.append("     0\n");
		sb.append(" 40\n");
		sb.append("0.0\n");
		sb.append("  0\n");
		sb.append("LTYPE\n");
		sb.append("  5\n");
		sb.append("15\n");
		sb.append("330\n");
		sb.append("5\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbLinetypeTableRecord\n");
		sb.append("  2\n");
		sb.append("BYLAYER\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  3\n");
		sb.append("\n");
		sb.append(" 72\n");
		sb.append("    65\n");
		sb.append(" 73\n");
		sb.append("     0\n");
		sb.append(" 40\n");
		sb.append("0.0\n");
		sb.append("  0\n");
		sb.append("LTYPE\n");
		sb.append("  5\n");
		sb.append("16\n");
		sb.append("330\n");
		sb.append("5\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbLinetypeTableRecord\n");
		sb.append("  2\n");
		sb.append("CONTINUOUS\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  3\n");
		sb.append("Solid line\n");
		sb.append(" 72\n");
		sb.append("    65\n");
		sb.append(" 73\n");
		sb.append("     0\n");
		sb.append(" 40\n");
		sb.append("0.0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("LAYER\n");
		sb.append("  5\n");
		sb.append("2\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("2\n");
		sb.append("  0\n");
		sb.append("LAYER\n");
		sb.append("  5\n");
		sb.append("50\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbLayerTableRecord\n");
		sb.append("  2\n");
		sb.append("0\n");
		sb.append(" 70\n");
		sb.append("0\n");
		sb.append("  6\n");
		sb.append("CONTINUOUS\n");
		sb.append("  0\n");
		sb.append("LAYER\n");
		sb.append("  5\n");
		sb.append("51\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbLayerTableRecord\n");
		sb.append("  2\n");
		sb.append("Layer_1\n");
		sb.append(" 70\n");
		sb.append("0\n");
		sb.append("  6\n");
		sb.append("CONTINUOUS\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("STYLE\n");
		sb.append("  5\n");
		sb.append("3\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     1\n");
		sb.append("  0\n");
		sb.append("STYLE\n");
		sb.append("  5\n");
		sb.append("11\n");
		sb.append("330\n");
		sb.append("3\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbTextStyleTableRecord\n");
		sb.append("  2\n");
		sb.append("STANDARD\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append(" 40\n");
		sb.append("0.0\n");
		sb.append(" 41\n");
		sb.append("1.0\n");
		sb.append(" 50\n");
		sb.append("0.0\n");
		sb.append(" 71\n");
		sb.append("     0\n");
		sb.append(" 42\n");
		sb.append("2.5\n");
		sb.append("  3\n");
		sb.append("txt\n");
		sb.append("  4\n");
		sb.append("\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("VIEW\n");
		sb.append("  5\n");
		sb.append("6\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("UCS\n");
		sb.append("  5\n");
		sb.append("7\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("APPID\n");
		sb.append("  5\n");
		sb.append("9\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     2\n");
		sb.append("  0\n");
		sb.append("APPID\n");
		sb.append("  5\n");
		sb.append("12\n");
		sb.append("330\n");
		sb.append("9\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbRegAppTableRecord\n");
		sb.append("  2\n");
		sb.append("ACAD\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("DIMSTYLE\n");
		sb.append("  5\n");
		sb.append("A\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     1\n");
		sb.append("  0\n");
		sb.append("DIMSTYLE\n");
		sb.append("105\n");
		sb.append("27\n");
		sb.append("330\n");
		sb.append("A\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbDimStyleTableRecord\n");
		sb.append("  2\n");
		sb.append("ISO-25\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append("  3\n");
		sb.append("\n");
		sb.append("  4\n");
		sb.append("\n");
		sb.append("  5\n");
		sb.append("\n");
		sb.append("  6\n");
		sb.append("\n");
		sb.append("  7\n");
		sb.append("\n");
		sb.append(" 40\n");
		sb.append("1.0\n");
		sb.append(" 41\n");
		sb.append("2.5\n");
		sb.append(" 42\n");
		sb.append("0.625\n");
		sb.append(" 43\n");
		sb.append("3.75\n");
		sb.append(" 44\n");
		sb.append("1.25\n");
		sb.append(" 45\n");
		sb.append("0.0\n");
		sb.append(" 46\n");
		sb.append("0.0\n");
		sb.append(" 47\n");
		sb.append("0.0\n");
		sb.append(" 48\n");
		sb.append("0.0\n");
		sb.append("140\n");
		sb.append("2.5\n");
		sb.append("141\n");
		sb.append("2.5\n");
		sb.append("142\n");
		sb.append("0.0\n");
		sb.append("143\n");
		sb.append("0.03937007874016\n");
		sb.append("144\n");
		sb.append("1.0\n");
		sb.append("145\n");
		sb.append("0.0\n");
		sb.append("146\n");
		sb.append("1.0\n");
		sb.append("147\n");
		sb.append("0.625\n");
		sb.append(" 71\n");
		sb.append("     0\n");
		sb.append(" 72\n");
		sb.append("     0\n");
		sb.append(" 73\n");
		sb.append("     0\n");
		sb.append(" 74\n");
		sb.append("     0\n");
		sb.append(" 75\n");
		sb.append("     0\n");
		sb.append(" 76\n");
		sb.append("     0\n");
		sb.append(" 77\n");
		sb.append("     1\n");
		sb.append(" 78\n");
		sb.append("     8\n");
		sb.append("170\n");
		sb.append("     0\n");
		sb.append("171\n");
		sb.append("     3\n");
		sb.append("172\n");
		sb.append("     1\n");
		sb.append("173\n");
		sb.append("     0\n");
		sb.append("174\n");
		sb.append("     0\n");
		sb.append("175\n");
		sb.append("     0\n");
		sb.append("176\n");
		sb.append("     0\n");
		sb.append("177\n");
		sb.append("     0\n");
		sb.append("178\n");
		sb.append("     0\n");
		sb.append("270\n");
		sb.append("     2\n");
		sb.append("271\n");
		sb.append("     2\n");
		sb.append("272\n");
		sb.append("     2\n");
		sb.append("273\n");
		sb.append("     2\n");
		sb.append("274\n");
		sb.append("     3\n");
		sb.append("340\n");
		sb.append("11\n");
		sb.append("275\n");
		sb.append("     0\n");
		sb.append("280\n");
		sb.append("     0\n");
		sb.append("281\n");
		sb.append("     0\n");
		sb.append("282\n");
		sb.append("     0\n");
		sb.append("283\n");
		sb.append("     0\n");
		sb.append("284\n");
		sb.append("     8\n");
		sb.append("285\n");
		sb.append("     0\n");
		sb.append("286\n");
		sb.append("     0\n");
		sb.append("287\n");
		sb.append("     3\n");
		sb.append("288\n");
		sb.append("     0\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("TABLE\n");
		sb.append("  2\n");
		sb.append("BLOCK_RECORD\n");
		sb.append("  5\n");
		sb.append("1\n");
		sb.append("330\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTable\n");
		sb.append(" 70\n");
		sb.append("     1\n");
		sb.append("  0\n");
		sb.append("BLOCK_RECORD\n");
		sb.append("  5\n");
		sb.append("1F\n");
		sb.append("330\n");
		sb.append("1\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbBlockTableRecord\n");
		sb.append("  2\n");
		sb.append("*MODEL_SPACE\n");
		sb.append("  0\n");
		sb.append("BLOCK_RECORD\n");
		sb.append("  5\n");
		sb.append("1B\n");
		sb.append("330\n");
		sb.append("1\n");
		sb.append("100\n");
		sb.append("AcDbSymbolTableRecord\n");
		sb.append("100\n");
		sb.append("AcDbBlockTableRecord\n");
		sb.append("  2\n");
		sb.append("*PAPER_SPACE\n");
		sb.append("  0\n");
		sb.append("ENDTAB\n");
		sb.append("  0\n");
		sb.append("ENDSEC\n");
		sb.append("  0\n");
		sb.append("SECTION\n");
		sb.append("  2\n");
		sb.append("BLOCKS\n");
		sb.append("  0\n");
		sb.append("BLOCK\n");
		sb.append("  5\n");
		sb.append("20\n");
		sb.append("330\n");
		sb.append("1F\n");
		sb.append("100\n");
		sb.append("AcDbEntity\n");
		sb.append("  8\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbBlockBegin\n");
		sb.append("  2\n");
		sb.append("*MODEL_SPACE\n");
		sb.append(" 70\n");
		sb.append("     0\n");
		sb.append(" 10\n");
		sb.append("0.0\n");
		sb.append(" 20\n");
		sb.append("0.0\n");
		sb.append(" 30\n");
		sb.append("0.0\n");
		sb.append("  3\n");
		sb.append("*MODEL_SPACE\n");
		sb.append("  1\n");
		sb.append("\n");
		sb.append("  0\n");
		sb.append("ENDBLK\n");
		sb.append("  5\n");
		sb.append("21\n");
		sb.append("330\n");
		sb.append("1F\n");
		sb.append("100\n");
		sb.append("AcDbEntity\n");
		sb.append("  8\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbBlockEnd\n");
		sb.append("  0\n");
		sb.append("BLOCK\n");
		sb.append("  5\n");
		sb.append("1C\n");
		sb.append("330\n");
		sb.append("1B\n");
		sb.append("100\n");
		sb.append("AcDbEntity\n");
		sb.append(" 67\n");
		sb.append("     1\n");
		sb.append("  8\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbBlockBegin\n");
		sb.append("  2\n");
		sb.append("*PAPER_SPACE\n");
		sb.append("  1\n");
		sb.append("\n");
		sb.append("  0\n");
		sb.append("ENDBLK\n");
		sb.append("  5\n");
		sb.append("1D\n");
		sb.append("330\n");
		sb.append("1B\n");
		sb.append("100\n");
		sb.append("AcDbEntity\n");
		sb.append(" 67\n");
		sb.append("     1\n");
		sb.append("  8\n");
		sb.append("0\n");
		sb.append("100\n");
		sb.append("AcDbBlockEnd\n");
		sb.append("  0\n");
		sb.append("ENDSEC\n");
		sb.append("  0\n");
		sb.append("SECTION\n");
		sb.append("  2\n");
		sb.append("ENTITIES\n");
		sb.append("  0\n");
		sb.append("LWPOLYLINE\n");
		sb.append("  5\n");
		sb.append("100\n");
		sb.append("100\n");
		sb.append("AcDbEntity\n");
		sb.append("  8\n");
		sb.append("Layer_1\n");
		sb.append(" 62\n");
		sb.append("7\n");
		sb.append("100\n");
		sb.append("AcDbPolyline\n");
		sb.append(" 90\n");
		sb.append("" + vertexesCount + "\n");
		sb.append(" 70\n");
		sb.append("1\n");

	}

}
